### ISSUE TITLE
Alexa Display Cards not working

### ISSUE THREAD

**Issue by Piflyer** [alexa/alexa-avs-sample-app#1167]
Hello,
I was able to get Alexa working on my Raspberry Pi, and I was wondering if it was possible to connect my Raspberry Pi Alexa to wifi through the Alexa app. Having an Echo at home, I can recall how to setup Alexa to wifi clearly. Also, how do you make the JavaClient button connect to a physical button from the GPIO pins? How do you make the Pi in setup mode? Do I need to create a special hotspot for the Pi to connect to the app? Thanks for any help.

**Comment by dhpp** [comment]
Hi @Piflyer, setup of an Amazon device such as Echo via the companion app is required, since the end user has no other way to configure the device.  If you are planning something similar in terms of product, then you will also need your own companion service to take care of this.

Could you elaborate further what you mean by a "JavaClient button"?  What would you expect this button to do?  And what do you mean by setup mode?  As I read your questions, I think they will generally be answered by either manually configuring your device with respect to connectivity, or implementing some kind of companion app to handle this for you.

**Comment by Piflyer** [comment]
I meant that is there any way to connect the virtual button int the JavaClient to trigger Alexa to a gpio button. Also, the display cards display the code, instead of the card itself under the Alexa Java pop up, is there any way around it?

**Comment by Piflyer** [comment]
When I ask Alexa what are pineapples, the text show up underneath, like a real card, but when I ask who what is an Amazon Echo, it shows the code.
