### ISSUE TITLE
Cannot retrieve token

### ISSUE THREAD

**Issue by sasherm13** [alexa/alexa-avs-sample-app#158]
I have the companion service running and execute "mvn exec:exec".  The website address comes up to register my device.  I enter it and follow the instructions.  this results in an error on the website and an error in the companion service.  Can someone help?
![screen shot 2016-04-23 at 5 34 25 pm](https://cloud.githubusercontent.com/assets/18625657/14764081/a499a83c-0978-11e6-90dc-a8c231686a68.png)

**Comment by ITJamie** [comment]
Im having the same issue. Did you manage to resolve this?

**Comment by sasherm13** [comment]
No I haven't.  Still stuck.

**Comment by tynick** [comment]
Im not getting prompted to register my device.

**Comment by keleric** [comment]
Are you running this on the latest reference app?

**Comment by Thilina711** [comment]
I am experiencing the same problem at the moment. how did you solve this?

**Comment by ajotwani** [comment]
@sasherm13 @Thilina711 @tynick @ITJamie just checking - you still having issues?

**Comment by ajotwani** [comment]
We're closing this Issue since the original poster (or another commenter) hasn't yet responded to the question or request made to them 14 days ago. We therefore assume that the user has lost interest or resolved the problem on their own.

Don't worry though; if this is an error, let us know with a comment and we'll be happy to reopen the Issue.

Thanks!
