### ISSUE TITLE
npm start issue

### ISSUE THREAD

**Issue by kevgagi** [alexa/alexa-avs-sample-app#176]
Could someone point me to the right direction on what i should do here? I get this message and when i try to activate the product via the link given on launching the client, after logging in to my amazon account and verifying it i just get an error message which im sure it has something to do with this. Thanks!~
![capture](https://cloud.githubusercontent.com/assets/19335781/15233025/07729dd4-185a-11e6-9a28-07627c37069c.PNG)

**Comment by ajotwani** [comment]
@kevgagi What's the error you get?

**Comment by visyone** [comment]
Hi I'am in same situation.

In companionService directory there aren't log file. What I can do?

**Comment by bat013** [comment]
@kevgagi that is the correct terminal screen. you need to open a new terminal to continue with the steps

**Comment by ajotwani** [comment]
@elstryan @kevgagi @visyone you still having issues with this?

**Comment by ajotwani** [comment]
We're closing this Issue since the original poster (or another commenter) hasn't yet responded to the question or request made to them 14 days ago. We therefore assume that the user has lost interest or resolved the problem on their own.

Don't worry though; if this is an error, let us know with a comment and we'll be happy to reopen the Issue.

Thanks!
