### ISSUE TITLE
npm will not start. 

### ISSUE THREAD

**Issue by chrispc05** [alexa/alexa-avs-sample-app#200]
I get the 'this node service needs to be running...' message and 'module.js:442' and 'cannot find module express' back. I have tried update & upgrade as well as the 6.x install to no avail. Any suggestions will be greatly appreciated. 

Here's a clip of what the npm start returned:

<img width="590" alt="errorcapture" src="https://cloud.githubusercontent.com/assets/19762643/15806628/63640d12-2b15-11e6-82c9-237c75d69969.PNG">

**Comment by sshtel** [comment]
you should install express.
$ npm install express

**Comment by chrispc05** [comment]
Thank you. Where shall it be installed?

**Comment by ajotwani** [comment]
@chrispc05 have you looked at this thread - https://github.com/amzn/alexa-avs-raspberry-pi/issues/97?

**Comment by ajotwani** [comment]
We're closing this Issue since the original poster (or another commenter) hasn't yet responded to the question or request made to them 14 days ago. We therefore assume that the user has lost interest or resolved the problem on their own.

Don't worry though; if this is an error, let us know with a comment and we'll be happy to reopen the Issue.

Thanks!

**Comment by yiyasha15** [comment]
@sshtel didnt work.
