### ISSUE TITLE
report: npm start error fix

### ISSUE THREAD

**Issue by sshtel** [alexa/alexa-avs-sample-app#203]
I tried to command 'npm start' to run node server(companionService) but it causes errors as other users already experienced.

I fixed package.json file like this and it works.
node -> nodejs

  "scripts": {
    "start": "nodejs ./bin/www"
  }

I don't understand why 'node' command does not work but 'nodejs' does instead.
It could be problem of nodejs on raspberry pi(ARM npm)

any other thought or solution?

**Comment by ajotwani** [comment]
@sshtel We've updated this project to include hands-free voice activation, using wake word engines from Sensory or KITT.AI. So, in addition to pushing a button to "start listening", you can now also just say the wake word "Alexa", much like the Amazon Echo. 

Perhaps give it another whirl, and let us know how it goes?

**Comment by keleric** [comment]
We're closing this Issue since the original poster (or another commenter) hasn't yet responded to the question or request made to them on Nov. 14th. We therefore assume that the user has lost interest or resolved the problem on their own.
Don't worry though; if this is an error, let us know with a comment and we'll be happy to reopen the Issue.
Thanks!
