### ISSUE TITLE
mvn exec:exec Error Message

### ISSUE THREAD

**Issue by hankp46** [alexa/alexa-avs-sample-app#216]
Alexa AVS is working fine but when I run mvn exec:exec I get the following error messages:
2016-06-23 13:57:42,061 ERROR FileManager (logs/application.log) java.io.FileNotFoundException: logs/application.log (Permission denied)
2016-06-23 13:57:42,068 ERROR Unable to invoke factory method in class class org.apache.logging.log4j.core.appender.RollingFileAppender for element RollingFile. java.lang.reflect.InvocationTargetException

I would like to clear these up. Any suggestions?

**Comment by yeralin** [comment]
Easiest solution (but not really safe one) just do "sudo chmod -R 777 ~/Desktop/alexa-avs-raspberry-pi-master/"

But the main thing is that you current user (most probably pi) doesn't have access to write in working directory, and by that command above it gives you whole 777 access to it.

Please ready more about permissions in linux, and also stuff about chmod.

Can be closed now

**Comment by ajotwani** [comment]
We're closing this Issue since the original poster (or another commenter) hasn't yet responded to the question or request made to them 14 days ago. We therefore assume that the user has lost interest or resolved the problem on their own.

Don't worry though; if this is an error, let us know with a comment and we'll be happy to reopen the Issue.

Thanks!
