### ISSUE TITLE
Token Retrieval Error

### ISSUE THREAD

**Issue by Thilina711** [alexa/alexa-avs-sample-app#221]
Hi,

On step 10-4 instead of device tokens ready i get the following error.

Token Retrieval Faliure

![image](https://cloud.githubusercontent.com/assets/20141176/16356974/b1754a4c-3b06-11e6-89b5-539b81bd4eaa.png)

**Comment by keleric** [comment]
Are you still seeing this problem? If so, are you on the latest reference app? Are you seeing the Amazon sign-in page?

**Comment by keleric** [comment]
It's possible there's something wrong with your client secret. Make sure there are no typos in the config.js file.

**Comment by Wingsnut** [comment]
I was having the same problem and there was something wrong with my client secret. Now how can I generate a new url to get a bearer token?

**Comment by ajotwani** [comment]
@Wingsnut Run the client and the server again.

$ cd /home/pi/Desktop/alexa-avs-raspberry-pi-master/samples/companionService
$ npm start

open new terminal

$ cd /home/pi/Desktop/alexa-avs-raspberry-pi-master/samples/javaclient
$ mvn exec:exec

Copy the URL, paste it into the browser.

**Comment by ajotwani** [comment]
We're closing this Issue since the original poster (or another commenter) hasn't yet responded to the question or request made to them 14 days ago. We therefore assume that the user has lost interest or resolved the problem on their own.

Don't worry though; if this is an error, let us know with a comment and we'll be happy to reopen the Issue.

Thanks!
