### ISSUE TITLE
Enable Amazon music playback

### ISSUE THREAD

**Issue by tomhannen** [alexa/alexa-avs-sample-app#223]
When I try to play music, I get a reply about "enabling iHeartRadio"...  I have no idea how to do that..

NB: I'm a Prime Music subscriber (in the UK).  I've requested Amazon Music in the device configuration... Will it get approved?  Will it work once approved? Thanks!

**Comment by Eddie-Hartman** [comment]
It just takes a while for it to get approved. Basically look at their requirements and say you don't download music or use it in any way against their policies and it will get approved.

**Comment by ajotwani** [comment]
We're closing this Issue since the original poster (or another commenter) hasn't yet responded to the question or request made to them 14 days ago. We therefore assume that the user has lost interest or resolved the problem on their own.

Don't worry though; if this is an error, let us know with a comment and we'll be happy to reopen the Issue.

Thanks!

**Comment by bodean712** [comment]
I've subscribed to Amazon Music for 6 months now with no issues until now. I can't listen to any of my songs on playlist or downloaded. After few seconds of the song attempting to upload it say, "cannot stream song". If Its a song I don't have downloaded and I attempt to download it says, download failed ERROR#223. Can anyone help me.
