### ISSUE TITLE
mvn exec:exec Blank Error Message

### ISSUE THREAD

**Issue by wegunterjr** [alexa/alexa-avs-sample-app#238]
I get all the way through the example, but when I run mvn exec:exec, I get a blank Error dialog without any words or instructions.  If I get rid of the error dialog by clicking on it, then the window you press play on continues to try and sync.  
- I had no issues with logging into Amazon
- Tokens were good (after copying the link and putting it into a browser on the pi)
- I updated the config.js with the Client ID and the Secret ID as instructed..

Thoughts? Suggestions?

**Comment by ajotwani** [comment]
@wegunterjr We've updated this project to include hands-free voice activation, using wake word engines from Sensory or KITT.AI. So, in addition to pushing a button to "start listening", you can now also just say the wake word "Alexa", much like the Amazon Echo. 

Perhaps give it another whirl, and let us know how it goes?

**Comment by keleric** [comment]
We're closing this Issue since the original poster (or another commenter) hasn't yet responded to the question or request made to them on Nov 14th. We therefore assume that the user has lost interest or resolved the problem on their own.
Don't worry though; if this is an error, let us know with a comment and we'll be happy to reopen the Issue.
Thanks!
