### ISSUE TITLE
Alexa voice isnt coming to bluetooth speaker

### ISSUE THREAD

**Issue by asavvin** [alexa/alexa-avs-sample-app#239]
Hello! I did follow to setup. Everything works on usb mic with speaker connected to rpi3 jack.
I am trying to use blue tooth speaker with mic. 

1) I found its only playing music from web radio trigger by alexa.amazon.com. It did not pass alexa responds. 
2) Does any body experience to use mic from blue tooth.

Thank you

**Comment by markbeee** [comment]
I have the same problem with the newest update/ upgrade of Jessie. Everything works fine, audio from other sources like youtube on my browser is working over bluetooth but I get no output when using Alexa. Any hint what to change in the Java code to get the output via Bluetooth?

**Comment by PaulGriffiths18** [comment]
I agree with this sound problem. I am using HDMI output to a tv.
I have found that just opening Sonic Pi before I click "start listening! will result in me being able to hear the prompt and also the reply - otherwise it is silent. 
As with the previous post other program work fine

**Comment by ajotwani** [comment]
We're closing this Issue since the original poster (or another commenter) hasn't yet responded to the question or request made to them 14 days ago. We therefore assume that the user has lost interest or resolved the problem on their own.

Don't worry though; if this is an error, let us know with a comment and we'll be happy to reopen the Issue.

Thanks!

**Comment by BHunter2889** [comment]
I just stumbled upon this from what I believe was a mistaken link to this issue, but this is another issue I came across as well... To answer this, I believe that the app doesn't allow for bluetooth audio output as when you run the install script, it asks whether you're using 3.5mm or HDMI. My guess is that whatever asks that in the install script sets one of those as the default output for Alexa. Without digging into the code, that's my best guess and I believe this issue is mistakenly closed since no one offered any support to the OP. Additionally, I feel contributors should possibly consider opening an internal ticket to add bluetooth support if it hasn't been done already. Or maybe one day I'll get around to it haha!
