### ISSUE TITLE
Error after clicking "Start Listening"

### ISSUE THREAD

**Issue by ricardo0221** [alexa/alexa-avs-sample-app#244]
I finished all the steps successfully, however, at the end when I click "Start Listening" I get a blank error message box and the alexa service stays processing forever until I close it. Can anyone help me out?

![screen shot 2016-08-03 at 1 41 53 am](https://cloud.githubusercontent.com/assets/13949270/17359470/89c44984-591b-11e6-9e76-d8328241ce5f.png)

**Comment by JacksonLv** [comment]
hi,have you fix the problem?I have the same error as you

**Comment by animeshp** [comment]
I'm also getting the same error!

**Comment by markbeee** [comment]
Might be your microphone is not working. Did you check (with arecord, aplay e.g.) if your microphone is recording properly?

**Comment by animeshp** [comment]
#180 probably suggests that it is not possible to use headphones as mic.

**Comment by ajotwani** [comment]
We're closing this Issue since the original poster (or another commenter) hasn't yet responded to the question or request made to them 14 days ago. We therefore assume that the user has lost interest or resolved the problem on their own.

Don't worry though; if this is an error, let us know with a comment and we'll be happy to reopen the Issue.

Thanks!
