### ISSUE TITLE
Alexa is not listening

### ISSUE THREAD

**Issue by WhiskeyThief** [alexa/alexa-avs-sample-app#246]
The install has gone fine with zero errors.  Section 10, step 4, I get the window opened that says "device tokens ready" and from section 8 I have the window open saying it is listening on port 3000.  
My assumption is if the token passed correctly I would see something in the window after "listening on port 3000", but I never do.
In the Alexa Voice Service java window I see:
Device: my_device DSN: 123456
Bearer Token: and a long string of characters.
But when I click on Start Listening I never get an audio prompt (I have forced the output to the 3.5 MM jack) and it never changes to "Stop Listening".

This is my first PI and Linux work, but I think I have followed the instructions well.  Any suggestions?

**Comment by Ztnepres** [comment]
I am getting the same error

**Comment by JadyLiu** [comment]
I have same issues, the error message is blank

**Comment by ajotwani** [comment]
@WhiskeyThief @JadyLiu We've updated this project to include hands-free voice activation, using wake word engines from Sensory or KITT.AI. So, in addition to pushing a button to "start listening", you can now also just say the wake word "Alexa", much like the Amazon Echo. 

Perhaps give it another whirl, and let us know how it goes?

**Comment by keleric** [comment]
We're closing this Issue since the original poster (or another commenter) hasn't yet responded to the question or request made to them on Nov 14th. We therefore assume that the user has lost interest or resolved the problem on their own.
Don't worry though; if this is an error, let us know with a comment and we'll be happy to reopen the Issue.
Thanks!
