### ISSUE TITLE
Repeated authorisation / registration requests

### ISSUE THREAD

**Issue by RobertSE** [alexa/alexa-avs-sample-app#248]
Hi,

I've set up the project successfully, however it repeatedly asks to register the device with Amazon, on reboot.

I know there are 2 types of authorisation, implicit grant and Authorization Code Grant does this have anything to do with it? 

Once I've registered once, how can I avoid having to register the device (RPi) again the next time I boot the Pi?

Any help would be great,
Thanks again for this project!

**Comment by keleric** [comment]
Several new releases of this sample app have occurred since this issue was created. I encourage you to look at the latest version and run automated_setup.sh! It makes it very easy to set up the app. Additionally, if you want to avoid signing in every time you start the app, look into the companionApp authorization method. That method will allow you to skip launching the companion service and signing in on every app start.
