### ISSUE TITLE
Pi Echo project 

### ISSUE THREAD

**Issue by Halfbreed1279** [alexa/alexa-avs-sample-app#255]
I am working on a pi echo project and I am receiving an error message when trying to register my device. I have made it up to step 10 I have made it past the "mvn exec:exec" and received the pop up window with the https://localhost address. Once I copy and paste into Url, I am getting an error page that the localhost can not connect or has been refused. Could anyone please assist me with this issue?

Thank you

**Comment by ajotwani** [comment]
have you checked to make sure you have the web settings - allowed origins, and allowed return URLs configured correctly at https://developer.amazon.com/edw/home.html#/avs/list?

**Comment by ajotwani** [comment]
We're closing this Issue since the original poster (or another commenter) hasn't yet responded to the question or request made to them 14 days ago. We therefore assume that the user has lost interest or resolved the problem on their own.

Don't worry though; if this is an error, let us know with a comment and we'll be happy to reopen the Issue.

Thanks!
