### ISSUE TITLE
how do you add hardware button

### ISSUE THREAD

**Issue by Sparklehart** [alexa/alexa-avs-sample-app#256]
i saw a tutorial that says to add a button to pin 3 and 18 to make a hardware button, but alas this doesn't seem to work. Is there a config that I am missing?

**Comment by hankp46** [comment]
The pin configuration can be confusing, changing depending on the model. I have a P3 and use 
GPIO 2 (7th down on left side if you use a cobbler). Make sure code reflects the right pin. Good luck!

Hank Poletto
hpoletto@cfl.rr.com

**Comment by Tiqni** [comment]
Hi,

I think that you are talking abour AlexaPi's push button, Correct?
Of course this will not work, until you hard-code the feature, by enabling the GPIO library, and making a loop waiting for the press event to start the microphone input.

**Comment by Sparklehart** [comment]
I got the setup.sh and one other file from the alpha and it worked nicely. Then I was even able to move the button to pin 23 as I needed 18 for something else

**Comment by ajotwani** [comment]
We're closing this Issue since the original poster (or another commenter) hasn't yet responded to the question or request made to them 14 days ago. We therefore assume that the user has lost interest or resolved the problem on their own.

Don't worry though; if this is an error, let us know with a comment and we'll be happy to reopen the Issue.

Thanks!
