### ISSUE TITLE
MVN Install command not found on VNC

### ISSUE THREAD

**Issue by Backlash5053** [alexa/alexa-avs-sample-app#258]
Everything worked fine but when I go to terminal from VNC and type in exactly as it states "MVN Install" it doesn't work. Any suggestions?

**Comment by Backlash5053** [comment]
I was able to download it directly on my pi but not through VNC for some reason.

**Comment by animeshp** [comment]
I was also facing the same issue but got it working after closing the VNC connection and reconnecting it.

**Comment by yeralin** [comment]
Restart your vnc/Reopen your terminal. Also check you $PATH, see whether mvn bin directory is there

**Comment by tommygibbons46** [comment]
@yeralin MVN install isn't working here either, how do I check my $PATH? Sorry for the novice question

**Comment by markbeee** [comment]
You can check your environment variables by either typing:

echo $PATH

or 

env | grep PATH

on the command line of the terminal.

**Comment by yeralin** [comment]
Also it should be "mvn install" not "MVN install". It is case sensitive.

**Comment by ajotwani** [comment]
We're closing this Issue since the original poster (or another commenter) hasn't yet responded to the question or request made to them 14 days ago. We therefore assume that the user has lost interest or resolved the problem on their own.

Don't worry though; if this is an error, let us know with a comment and we'll be happy to reopen the Issue.

Thanks!
