### ISSUE TITLE
Max Requests Error

### ISSUE THREAD

**Issue by pimatrix314** [alexa/alexa-avs-sample-app#265]
After I say the command, it processes for a while and then spits back a max requests error

**Comment by erikhopf-amzn** [comment]
@pimatrix314 -- can you post the logs?

**Comment by ajotwani** [comment]
We're closing this Issue since the original poster (or another commenter) hasn't yet responded to the question or request made to them 14 days ago. We therefore assume that the user has lost interest or resolved the problem on their own.

Don't worry though; if this is an error, let us know with a comment and we'll be happy to reopen the Issue.

Thanks!
