### ISSUE TITLE
after rest doesn't work automatically

### ISSUE THREAD

**Issue by ghost73** [alexa/alexa-avs-sample-app#275]
why after rest the raspberry cannot  listening automatically?

**Comment by ajotwani** [comment]
@ghost73 not sure what you mean by "after rest"?

**Comment by ghost73** [comment]
I meam after after reboot again the rasberry pi.
The services not start automatically

**Comment by ajotwani** [comment]
That is correct. You'd need to follow the instructions to run the companion service, the client, and the wake word agent after your reboot.

**Comment by ghost73** [comment]
All over again? There is no script to create a file that will run automatically,after rebooting the raspberry pi?

**Comment by swilso793** [comment]
you can do it diy style. It's not really that hard. You can use screen or tmux to open each line in a new window

**Comment by ghost73** [comment]
i dont know how to to, it only needed to do the step 7 from this websit: https://github.com/alexa/alexa-avs-sample-app/wiki/Raspberry-Pi

**Comment by ajotwani** [comment]
We're closing this Issue since the original poster (or another commenter) hasn't yet responded to the question or request made to them 14 days ago. We therefore assume that the user has lost interest or resolved the problem on their own.

Don't worry though; if this is an error, let us know with a comment and we'll be happy to reopen the Issue.

Thanks!
