### ISSUE TITLE
pandora with alexa on raspberry pi

### ISSUE THREAD

**Issue by mtasatcom** [alexa/alexa-avs-sample-app#288]
I have alexa working on the raspberry pi but when I ask it to play a station on Pandora It say Pandora stations are not supported on  this device. Do I need another program installed to allow this?

**Comment by bill-orange** [comment]
I am pretty sure the answer is no.

I loaded the Alexa administration app on my iPhone, under settings is a tab for Music, under music Pandora is listed.  Unfortunately if you click on it, it says words to the effect of "not supported on your device".  iHeart radio is supported.  You can also play music in your Amazon music uploads if you get Amazon's approval.  

I looked for an IFTTT connection for Pandora.  No luck there either.  

Since Pandora is a competitor to Amazon Music, I would not look for this situation to change.

As you probably guessed, I also wanted to use Pandora.

**Comment by keleric** [comment]
Unfortunately, Pandora is only supported on the Echo and Tap. AVS does not currently support it. Sorry!

**Comment by erikhopf-amzn** [comment]
resolved

**Comment by mtasatcom** [comment]
Thanks
