### ISSUE TITLE
Android Companion can't be installed 

### ISSUE THREAD

**Issue by briandbl** [alexa/alexa-avs-sample-app#294]
HI 

I got the following the errors. when I use the Android studio to install the androidCompanionapp.

Error:Execution failed for task ':app:packageDebug'.

> Failed to read key androiddebugkey from store "/home/brian/projects/alexa/alexa-avs-sample-app/samples/androidCompanionApp/app/keystore.jks": Cannot recover key

who know the reasons? Currently I can't run the alexa voice services.

**Comment by keleric** [comment]
Does this help? http://stackoverflow.com/questions/14606837/cannot-recover-key

It's probably a password problem. You might have luck regenerating it and paying very close attention to the password prompts.

**Comment by keleric** [comment]
We're closing this Issue since the original poster (or another commenter) hasn't yet responded to the question or request made to them on Oct 10th. We therefore assume that the user has lost interest or resolved the problem on their own.
Don't worry though; if this is an error, let us know with a comment and we'll be happy to reopen the Issue.
Thanks!
