### ISSUE TITLE
Request NO GUI version

### ISSUE THREAD

**Issue by ghvader** [alexa/alexa-avs-sample-app#314]
is it possible to make this work without a X11 / gui setup?
it would be nice to have this all working with pure CLI on a headless / ssh setup.

**Comment by keleric** [comment]
#86 has some suggestions for a previous version of the app to get it working in a headless setup.

**Comment by ghvader** [comment]
thanks for the reply keleric. i was hoping for a non X11 version. this should be able to be done.. i don't code in java though.. so that's the sticking point for.. appreciate the extra info in that thread though.

**Comment by erikhopf-amzn** [comment]
@ghvader Alternatively, you could use an Android or iOS companion app instead of the Node service. Sample code is included in the repo -- see the Wiki for build instructions.

**Comment by brenthunter** [comment]
Yeah, it would be good to be able to use this in a completely automated fashion, without the need to go to a website, need X11 display, etc.

**Comment by renekliment** [comment]
You can try https://github.com/alexa-pi/AlexaPi It still uses the previous API version, but it has some sexy features - like running completely headless.

**Comment by cpswan** [comment]
Closed by mistake just after applying the Feature Request label? I'm not seeing any commit to code or docs that would allow headless operations.

**Comment by keleric** [comment]
No, this was closed purposefully. We don't use Github to track feature requests. The request has been submitted internally, and will be scheduled relative to other priorities. It's a good idea that a lot of people want, but it has to be balanced against improving the actual service and developing other highly requested features!

**Comment by cpswan** [comment]
Fair enough, but if you're going to close issues here for stuff that hasn't actually been fixed then it might be worth leaving a brief note to explain what's happening. Otherwise people watching the issue (like I was) get left in the dark, and people later on wanting the feature tripping across the old closed issue will get confused.

Your project, your rules, your tools, but if you don't tell people what's going on they'll just hassle you with stupid questions all the time (and fewer people will offer to help).

**Comment by keleric** [comment]
Thanks for the input. We'll try to do that in the future.
