### ISSUE TITLE
Wake word detected but no beep

### ISSUE THREAD

**Issue by utamav** [alexa/alexa-avs-sample-app#317]
I am running Alexa AVS on Raspberry Pi B. I have successfully setup everything. I have the voice recognition engine running and I can see the engine detecting the wake word:

`INFO: KittAiSnowboyWakeWordEngine: Wake Word Detected`
`INFO: ===> WakeWordAgent: wake word detected <===`

But I don't hear any feedback in the form of a beep. I tried asking a question as well but no response. I am connected to speaker. I have validated that the audio setup is working fine by playing an audio file. 

I am using Logitech U430 USB gaming headset for mic and speakers. 

Any help would be appreciated.

**Comment by bill-orange** [comment]
Can you plug speakers into the PI audio jack at least to test? Your audio is probably coming out there.

**Comment by utamav** [comment]
Yes. I tried that too. Still no audio.

**Comment by bill-orange** [comment]
I tried switching to a USB sound device to get better audio. It did not work. When I attempted to change everything back to the PI audio device it still did not work. For some reason once you redirect Audio away from the default, it does not seem to return Alex output to operation. 

I may have encounter the problem you encountered. 

There should be a way to revert to the default. There have been approached offered in other thread that appear to only work in some cases. 

Does anyone else have an idea?

I need up reformatting the uSD and starting fresh in the default hardware configuration using the PIs audio jack.

**Comment by keleric** [comment]
Unfortunately, we've encountered issues with audio output on Raspberry Pi's when trying to output audio via USB. That's why it's not a supported mechanism for outputting audio. That's not to say it's impossible to get working (you can try searching Github for other people attempting to do the same). However, it does mean that I'm unable to offer effective support for debugging this issue. If you have run the automated_install.sh script and are using HDMI or 3.5mm to output audio and it still doesn't work, please reopen this issue so we can investigate! Thanks.
