### ISSUE TITLE
Could I be able to connect my phone with bluetooth on raspberry pi and play music 

### ISSUE THREAD

**Issue by Teamtyler2** [alexa/alexa-avs-sample-app#319]
Whould it be possible to connect my phone to the bluetooth on my raspberry pi and play music on my phone and have it like a speaker like amazon echo

**Comment by erikhopf-amzn** [comment]
While not official, lifehacker has provided instructions for enabling AirPlay on the Pi here: http://lifehacker.com/how-to-build-your-own-amazon-echo-with-a-raspberry-pi-1787726931

**Comment by Teamtyler2** [comment]
@erikhopf-amzn Thank you so much Sir, i will try it

**Comment by Teamtyler2** [comment]
@erikhopf-amzn im having a issue with github thought on it theres No Make File or meta file

**Comment by erikhopf-amzn** [comment]
@Teamtyler2 not quite sure I understand your last question. Can you provide some additional details on what issues you're encountering?

**Comment by Teamtyler2** [comment]
@erikhopf-amzn there is no build file when I run it and no meta file the guy who made it is looking into it ig

**Comment by Dtrieb** [comment]
@Teamtyler2 : 
Look [here](http://lifehacker.com/how-to-build-your-own-amazon-echo-with-a-raspberry-pi-1787726931)

**Comment by keleric** [comment]
We're closing this Issue since the original poster (or another commenter) hasn't yet responded to the question or request made to them 14 days ago. We therefore assume that the user has lost interest or resolved the problem on their own.
Don't worry though; if this is an error, let us know with a comment and we'll be happy to reopen the Issue.
Thanks!
