### ISSUE TITLE
The Amazon Alexa app is refusing to co-operate.

### ISSUE THREAD

**Issue by CHBoyle** [alexa/alexa-avs-sample-app#333]
Last night, I set up the Windows Alexa as a test, and the Amazon Alexa app on my android phone listed the device as 'online' and was doing all the card stuff it's supposed to.
Today, I set up the Raspberry Pi version, and now neither device (pi alexa or windows alexa) will display as online when turned on.
Wat.

**Comment by erikhopf-amzn** [comment]
@CHBoyle a few quick questions:

* Even though your Pi doesn't show up as online, can you make requests to Alexa and get responses?
* Are you using the same Product ID for both?

**Comment by CHBoyle** [comment]
@erikhopf-amzn 
I can, but I can't enable any skills other than ones I've made myself, see cards on the app, et cetera.
No, different Product ID, different device on the developer console.

**Comment by b33rgit** [comment]
Are you in the U.K.? I bet uve got the same issue as me (see 343). My device initially showed online but as soon as I updated the location it started showing offline in Alexa. I've narrowed it down to something to do with the apps and services changing on Amazon but can't resolve it

**Comment by keleric** [comment]
We're closing this Issue since the original poster (or another commenter) hasn't yet responded to the question or request made to them on Oct 22nd. We therefore assume that the user has lost interest or resolved the problem on their own.
Don't worry though; if this is an error, let us know with a comment and we'll be happy to reopen the Issue.
Thanks!
