### ISSUE TITLE
[Question]About while (controller.eventRunning()){}

### ISSUE THREAD

**Issue by nezen** [alexa/alexa-avs-sample-app#344]
May I ask what's the purpose of this [line](https://github.com/alexa/alexa-avs-sample-app/blob/master/samples/javaclient/src/main/java/com/amazon/alexa/avs/AVSAudioPlayer.java#L348) and this [line](https://github.com/alexa/alexa-avs-sample-app/blob/master/samples/javaclient/src/main/java/com/amazon/alexa/avs/AVSAudioPlayer.java#L384)? 
I know it's already commented, but I'm confused why it's necessary to wait for any pending events to finish. A further explanation would be appreciated, thanks!

**Comment by ajotwani** [comment]
We're closing this Issue since the original poster (or another commenter) hasn't yet responded to the question or request made to them 14 days ago. We therefore assume that the user has lost interest or resolved the problem on their own.

Don't worry though; if this is an error, let us know with a comment and we'll be happy to reopen the Issue.

Thanks!
