### ISSUE TITLE
Does anyone execute  AVS at sun gnu java runtime environment (not openJDK)?

### ISSUE THREAD

**Issue by wonderjason** [alexa/alexa-avs-sample-app#347]
Does anyone execute  AVS at sun gnu java runtime environment (not openJDK)?
Thanks for help for me?

**Comment by ajotwani** [comment]
We're closing this Issue since the original poster (or another commenter) hasn't yet responded to the question or request made to them 14 days ago. We therefore assume that the user has lost interest or resolved the problem on their own.

Don't worry though; if this is an error, let us know with a comment and we'll be happy to reopen the Issue.

Thanks!
