### ISSUE TITLE
Error while:-  mvn exec:exec --- Failed to execute goal org.codehaus.mojo:exec-maven-plugin:1.2.1

### ISSUE THREAD

**Issue by karthikmr147** [alexa/alexa-avs-sample-app#354]
I get the below error when I try to execute the javaclient. Please share comments on solving the problem

Karthiks-MacBook-Air:javaclient karthik$ mvn exec:exec
[INFO] Scanning for projects...
[INFO]                                                                         
[INFO] ------------------------------------------------------------------------
[INFO] Building Alexa Voice Service Sample Java Client 20160207.1
[INFO] ------------------------------------------------------------------------
[INFO] 
[INFO] --- exec-maven-plugin:1.2.1:exec (default-cli) @ sample-java-client ---
Exception in thread "main" javax.json.stream.JsonParsingException: Unexpected char 10 at (line no=2, column no=32, offset=33)
	at org.glassfish.json.JsonTokenizer.unexpectedChar(JsonTokenizer.java:532)
	at org.glassfish.json.JsonTokenizer.readString(JsonTokenizer.java:189)
	at org.glassfish.json.JsonTokenizer.nextToken(JsonTokenizer.java:376)
	at org.glassfish.json.JsonParserImpl$ObjectContext.getNextEvent(JsonParserImpl.java:255)
	at org.glassfish.json.JsonParserImpl$StateIterator.next(JsonParserImpl.java:172)
	at org.glassfish.json.JsonParserImpl.next(JsonParserImpl.java:149)
	at org.glassfish.json.JsonReaderImpl.readObject(JsonReaderImpl.java:177)
	at org.glassfish.json.JsonReaderImpl.readObject(JsonReaderImpl.java:103)
	at com.amazon.alexa.avs.config.DeviceConfigUtils.readConfigFile(DeviceConfigUtils.java:64)
	at com.amazon.alexa.avs.config.DeviceConfigUtils.readConfigFile(DeviceConfigUtils.java:50)
	at com.amazon.alexa.avs.AVSApp.<init>(AVSApp.java:94)
	at com.amazon.alexa.avs.AVSApp.main(AVSApp.java:89)
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 9.251 s
[INFO] Finished at: 2016-11-01T23:13:59-07:00
[INFO] Final Memory: 11M/113M
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal org.codehaus.mojo:exec-maven-plugin:1.2.1:exec (default-cli) on project sample-java-client: Command execution failed. Process exited with an error: 1 (Exit value: 1) -> [Help 1]
[ERROR] 
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR] 
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MojoExecutionException

**Comment by BrianDurward** [comment]
I had the same problem.  I solved the problem by running the 3 separate command line instructions using vncserver(run on the pi) and vncviewer on my linux pc.  I was unsuccessful using SSH - not sure why.
Good luck.  The jokes are great by the way.

**Comment by karthikmr147** [comment]
Thank you for the reply.I am not using any pi or mobile devices as server or client. I am running the server on my mac which is listening at 3000 and trying to run the javaclient. Encountering the above issue. Could you please guide me to debug the issue ? Where should i start looking ? @BrianDurward

**Comment by karthikmr147** [comment]
hey @BrianDurward  .. I got it fixed ! there were some problems with the config file of mine. The syntax was wrong interpreted because of the different text editor.

**Comment by BrianDurward** [comment]
Great I have no Apple knowledge.
Brian

**Comment by alexsalnikov** [comment]
Validate your file at alexa-avs-sample-app\samples\javaclient\config.json
if it have right characters, maybe use simple name for 
"productId":"<!!!your-product-id!!!>",

**Comment by BeaurCed** [comment]
@karthikmr147  Can you be more specific about the syntax of your config file because I have the same issue as you.
Thank you

**Comment by ypotier** [comment]
Yes, the instruction for the productID are not clear. Can you please provide an example and explain the format?

**Comment by alexsalnikov** [comment]
Hi guys if you look inside automated_install.sh
you suppose to fill these 3 lines with ones you got when you created 
amazon security profile 

# on web page it will be Device Type ID, try to use simple name as one word
ProductID=my_rpi

ClientID=amzn1.application-oa2-client.xxxxxxxxxxxxxxxxxxxxxxxxxxxxxx

ClientSecret=xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx

* instead of xxx you should get mix of numbers and letters

then you run ./automated_install.sh so it will copy this info to the right places
one of the file that should be updated is samples\companionService\config.js
you can open it and see if it go the right: ProductID, ClientID, ClientSecret

file content should be something like
var config = {
    clientId: "amzn1.application-oa2-client.xxxxxxxxxxxxxxxxxxxxxxxxxxxxxx",
    clientSecret: "xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx",
    redirectUrl: 'https://localhost:3000/authresponse',
    lwaRedirectHost: "amazon.com",
    lwaApiHost: "api.amazon.com",
    validateCertChain: true,
    sslKey: "/home/pi/Desktop/alexa-avs-sample-app/samples/javaclient/certs/server/node.key",
    sslCert: "/home/pi/Desktop/alexa-avs-sample-app/samples/javaclient/certs/server/node.crt",
    sslCaCert: "/home/pi/Desktop/alexa-avs-sample-app/samples/javaclient/certs/ca/ca.crt",
    products: {
        "my_rpi": ["1xxxxxxxxxx"],
    },
};

**Comment by keleric** [comment]
The initial error was because your config.json file was not formatted properly. Please look at it and try to figure out why it is not valid JSON. Alternatively, use the automated_install.sh script, which should take care of most of these problems for you! I'm closing this issue - if you run into problems, feel free to open up a new one!

**Comment by stnschrdr** [comment]
I had the same problem and figured out the issue. It was a VLC error I had was because the VLC website provides only the 32-bit OS version for the download on their main page. To get the 64-bit version I had to scroll down to the bottom of the web page and click on 'Windows' OS which took me to another webpage which had the Windows 64-bit option from their Download pull-down menu options.
