### ISSUE TITLE
Amazon service has been down for several days

### ISSUE THREAD

**Issue by gamefrenza** [alexa/alexa-avs-sample-app#362]
Following the instruction installing Alexa on my Raspberry Pi3, stuck at the following step due to error from Amazon service. It's been a couple of days. 
At Step 7: Run your web service, sample app and wake word engine 
  Terminal Window 2
    Step 4:  When trying to connect to Amazon service with the following URL, keep getting error screen from Amazon service. 

https://na.account.amazon.com/ap/oa?appActionToken=ghGEmEHgji3TpSVQfOS9j2FBXY728j3D&appAction=actionField&savedParameters=xxxxx&openid.pape.auth_policies=http%3A%2F%2Fschemas.openid.net%2Fpape%2Fpolicies%2F2007%2F06%2Fnone&language=en_US&consentApproved=

Please advise how to report the issue to Amazon Alexa service team to fix the issue.

Thanks a lot.

**Comment by elstryan** [comment]
Which mechanism are you using to authenticate? Is the node service. Have you gone through the steps here: https://github.com/alexa/alexa-avs-sample-app/wiki/Linux#6a---nodejs

**Comment by keleric** [comment]
We're closing this Issue since the original poster (or another commenter) hasn't yet responded to the question or request made to them on Nov 7th. We therefore assume that the user has lost interest or resolved the problem on their own.
Don't worry though; if this is an error, let us know with a comment and we'll be happy to reopen the Issue.
Thanks!
