### ISSUE TITLE
Start Alexa automatically on boot

### ISSUE THREAD

**Issue by niallmca** [alexa/alexa-avs-sample-app#367]
Anyone figured out how to do this...?
Major pain having to get tokens and run three shell scripts manually from a new terminal everytime Rasp Pi is rebooted.

**Comment by roccomuso** [comment]
yeah it's pretty uncomfortable/useless this way. You gotta do manually all the steps on boot. I Still don't understand why they built a java application instead of a bin with a node.js wrapper.

**Comment by niallmca** [comment]
I agree :)
A node.js solution would be so much better than the current Java implementation.
Are there any plans to 'node.js-tify' this ???

**Comment by TheFuz** [comment]
This is something I am looking for as well. Having to configure my Pi everytime I start it is a hassle. Is there a way we can have a script that does the startup using the existing application?

**Comment by niallmca** [comment]
I believe the other Alexa project (Sam minchin) for Rasp Pi can startup automatically.  Don't know if that could be applied to this?

**Comment by qkzk** [comment]
Someone did it a while ago and it worked fine for monthes. I managed to kill the raspberry yesterday so here I am, looking for a simpler approch. If anyone still interested, the details are at the end of his hackster.io projet : https://www.hackster.io/xelfer/time-machine-a079fa

**Comment by ambrosechoy** [comment]
@qkzk Have you come across a simpler approach on how to do this yet? If so, would you care sharing it with me? Thanks.

**Comment by niallmca** [comment]
no I haven't :(
It's a real pain starting this every time with three different terminals and a browser.
In my view, this sample app should be converted from Java to NodeJS.

If it doesn't get easier to use, then I can see the maker community moving
away from Amazon and towards Google or Siri equivalent.

**Comment by OptimalPaul** [comment]
I don't think there is any reason you couldn't run the companion app on another server and having it serving tokens when the pi starts up.  This is something I am looking at.  The other alternative is the android companion app that is published in the code, but doesn't seem to be supported yet.

**Comment by qkzk** [comment]
Sorry @ambrosechoy I was busy with work... No I haven't found anything simpler yet.
I'm going to look for it again and try again the AlexaAppCompanion thingy if I can't

**Comment by qkzk** [comment]
Well... I'm giving up Alexa for today.
4 hours later, i'm still stucked at the companionApp certification.
I don't understand what's wrong but I get : 
`java.security.cert.CertPathValidatorException: Trust anchor for certification path not found`
on the companionApp everytime.

I did everything like the first time except updating the `alpn-boot.version` from pom.xml
My jdk version is `8u111` (from dkpg --list | grep -i jdk) wich means 1.8.0u111 but I can't find the corresponding version in [alpn-versions](http://www.eclipse.org/jetty/documentation/current/alpn-chapter.html#alpn-versions).

Since I need the full name of the build, I can't guess it.

It may be that or alpn-boot is not supported anymore... or the companionApp is not supported anymore... or I failed somewhere.

Since it's only a fun projet ("Alexa... tell me a joke !") to have fun with friends 3 times a year.. I can live without it.

**Comment by umma08** [comment]
#471 seems to have some success at this (still being refined but users have seemed to have gotten it working). Haven't tried myself yet, but it is on the to-do list.

**Comment by keleric** [comment]
@qkzk FWIW, the companion app feature works and is fully-supported. If you're seeing CertValidationException, try the following:
- The ca.crt file generated by the scripts above should be copied to src/main/res/raw/ca.crt. It needs to exactly match what the Java sample app has. The automated_install.sh script should do this for you, but it's easy enough to do it manually just to make sure it was done correctly.
- The Java client needs to be running before running the companion app

**Comment by keleric** [comment]
Closing this issue because I've added this feature request to our internal tracking system.
