### ISSUE TITLE
Crash in RasPi Terminal #2

### ISSUE THREAD

**Issue by Simon-Chase** [alexa/alexa-avs-sample-app#369]
For some reason the script used for terminal window 2 in the raspberry pi code doesn't work anymore. It used to. https://puu.sh/sffbv/5bc5524cbc.png

**Comment by alexsalnikov** [comment]
From your crash log it's seems like you have problem with parsing of alexa-avs-sample-app\samples\javaclient\config.json file
as suggestion clone alexa-avs-sample-app to other folder and run again automated_install
or hand edit your config.json

{
    "productId":"<!!!your-product-id!!!>",
    "dsn":"1xxxxxxxxxx",
    "provisioningMethod":"companionService",
    "wakeWordAgentEnabled":true,
    "avsHost":"https://avs-alexa-na.amazon.com",
    "companionApp":{
        "localPort":8443,
        "lwaUrl":"https://api.amazon.com",
        "sslKeyStore":"/home/pi/alexa-avs-sample-app/samples/javaclient/certs/server/jetty.pkcs12",
        "sslKeyStorePassphrase":""
    },
    "companionService":{
        "serviceUrl":"https://localhost:3000",
        "sslClientKeyStore":"/home/pi/alexa-avs-sample-app/samples/javaclient/certs/client/client.pkcs12",
        "sslClientKeyStorePassphrase":"",
        "sslCaCert":"/home/pi/alexa-avs-sample-app/samples/javaclient/certs/ca/ca.crt",
        "sessionId":"<!!!your-session-id!!!>"
    }
}

**Comment by keleric** [comment]
We're closing this Issue since the original poster (or another commenter) hasn't yet responded to the question or request made to them 14 days ago. We therefore assume that the user has lost interest or resolved the problem on their own.

Don't worry though; if this is an error, let us know with a comment and we'll be happy to reopen the Issue.

Thanks!
