### ISSUE TITLE
mvn exec:exc

### ISSUE THREAD

**Issue by varunm100** [alexa/alexa-avs-sample-app#370]
Screenshot - 

![2016-11-12](https://cloud.githubusercontent.com/assets/19439575/20235035/a9bc4ffc-a8ad-11e6-9482-88ea4c9cb26c.png)

**Comment by varunm100** [comment]
Any help would be appreciated :)

**Comment by keleric** [comment]
There's something wrong with your path. It can't find the client keystore. Try using an absolute path instead of a relative one.

**Comment by varunm100** [comment]
what do you mean by the "absolute path" sorry I am a complete NOOB

**Comment by pierceds** [comment]
Instead of starting your keystore path with just "alexa-avs-sample-app\\..." try starting it with its full location on your computer. Example: "C:\\Users\\varun\\alexa-avs-sample-app\\..."

**Comment by keleric** [comment]
We're closing this Issue since the original poster (or another commenter) hasn't yet responded to the question or request made to them on Nov 18th. We therefore assume that the user has lost interest or resolved the problem on their own.
Don't worry though; if this is an error, let us know with a comment and we'll be happy to reopen the Issue.
Thanks!
