### ISSUE TITLE
Android companion app not building

### ISSUE THREAD

**Issue by NickWright25** [alexa/alexa-avs-sample-app#411]
`Error:(15, 1) Execution failed for task ':app:checkForRequiredFiles'.
> The API Key file does not exist. Please make sure ./src/main/assets/api_key.txt has been created and populated with the proper values from the Security Profile you created.`

This is the only error I get when I try to open the Android companion app in Android studio. Is there something i'm doing wrong to cause this or is it a bug?

**Comment by max-erler** [comment]
You'll need to add an API key to the project in order to run the android companion app. Instructions on how to do this can be found here: https://github.com/alexa/alexa-avs-sample-app/wiki/Linux#5b---build-and-run-an-android-companion-app-authentication. There are other instructions depending on operating system, but all can be found in this repository's wikis.
