### ISSUE TITLE
git pull issue 

### ISSUE THREAD

**Issue by mohaggag** [alexa/alexa-avs-sample-app#512]
Updating 587ddd4..598fb51
error: Your local changes to the following files would be overwritten by merge:
automated_install.sh
samples/javaclient/config.json
samples/javaclient/install-java8.sh
samples/javaclient/pom.xml
Please, commit your changes or stash them before you can merge.
Aborting

thats what i got when i try to git pull

**Comment by Alexnagel** [comment]
This is no issue, but expected behaviour. 
When setting up Alexa you have altered automated_install.sh, running that in turn has edited other files. 

The easiest way to continue is to stash the changes, pull master once again and the pop the changes.
As far as I know, the pom.xml and install-java8.sh can be reset to their original state, as such:
- `git checkout samples/javaclient/install-java8.sh`
- `git checkout samples/javaclient/pom.xml`

After this you can stash, `git stash`, and pull again. When that's done you can `git stash pop`.
You might get a merge conflict which you'll need to fix. Check https://help.github.com/articles/resolving-a-merge-conflict-using-the-command-line/ for more info

**Comment by mohaggag** [comment]
yes thanks alot 
i am sorry i am not that good on git 
i was using
` git `checkou`
not 
`git` checkout `samples/javaclient/install-java8.sh`
