### ISSUE TITLE
Unknown CMake command "target_include_directories"

### ISSUE THREAD

**Issue by trisys3** [alexa/alexa-avs-sample-app#527]
I keep getting an error when I try to run the `automated_install`:

```CMake Error at CMakeLists.txt:36 (target_include_directories):
  Unknown CMake command "target_include_directories".

-- Configuring incomplete, errors occurred!
```

I get this twice during the build process, and no other errors (except `This OS is not Raspbian` when trying to install Java, but that is unrelated).

This seems to be when installing the wake word agents, which is, I suspect, why there is no `wakeWordAgent` file in my `samples/wakeWordAgent/src` folder, and therefore I can not install the wake word agent.

Another minor issue is that, at the end of the `automated_install`, I am stuck in the `samples/wakeWordAgent/tst` folder, and have to navigate out to continue setting up. I suspect this is also directly related to the issues during installation.

I tracked the problem down to an outdated but still supported version of `cmake`. The first version that supports `target_include_directories` is version `2.8.12`, but my Pi's version is `2.8.9`. For reference, the newest stable version is `3.7.2`. According to an [issue](https://github.com/weidai11/cryptopp) over at `Crypto++`, version `2.8.12` is too new, but `StackOverflow` has a question about emulating `target_include_directories` pre-version `2.8.12`. Unfortunately, I have not worked with `cmake`, so I won't be of much help.

**Comment by Alexnagel** [comment]
I'm guessing your not using a clean install of Raspbian then? Also guessing by the cmake version your still on Wheezy, if it's Raspbian you're using. 
The easy way would be upgrade to Jessie. As in Jessie the current version is 3.0.2-1

Otherwise you could do something like mentioned here: http://askubuntu.com/questions/610291/how-to-install-cmake-3-2-on-ubuntu-14-04

**Comment by trisys3** [comment]
Yes, this is a relatively old Raspberry Pi. It is Pi 2 Model B, which is still supported by this repository. I upgraded to `Jessie` at one point, but perhaps not completely. I will try to find the directions I followed, as they may have mentioned caveats, etc.

**Comment by Alexnagel** [comment]
Ah as you're already on Jessie, have you tried running `sudo apt-get update && sudo apt-get upgrade`?

**Comment by trisys3** [comment]
Hmmm... I thought I upgraded Raspberry Pi to Jessie, but it looks like I did not. I will try that, then remove the repository and retry, then tell you the results and (hopefully) close this issue.

**Comment by Alexnagel** [comment]
Ahaa, the pi foundation does recommend to do a clean install. But if you really really want to upgrade the wheezy image they have a _unsupported_ way to do so.  See https://www.raspberrypi.org/blog/raspbian-jessie-is-here/ (scroll to the last bit for the recommendation and alternative upgrade path)

**Comment by trisys3** [comment]
I saw that, and am currently upgrading as we speak.

**Comment by trisys3** [comment]
The new packages filled up my drive, so it looks like I have to get a bigger SD card. I am closing, but will reopen if I have more problems.

**Comment by bogdancraciun** [comment]
I am having the same issues with a fresh install of raspbian jessy. as far as I understand before running the automated_installer.sh I need to install dependencies (which are mentioned only in the Linux install guide section, but not in the RPi). In order to make it work, I had to install everything by hand, but I don't have the wake word enabled. Does anybody knows how to compile/install sensory/kitty by hand? I have looked on their website and says that I need to download a precompiled package, but I don't know how to make it work with Alexa...

**Comment by Alexnagel** [comment]
The `automated_installer.sh` also installs dependencies, well apart of wiringPi. 
Did you run it?


running `cmake . && make -j4` in the wakeword src directory should build it.

**Comment by bogdancraciun** [comment]
I've already tried cmake . followed by a make -j4, but I get the following errors:

In file included from /home/pi/Desktop/alexa-avs-sample-app/samples/wakeWordAgent/src/WakeWordEngineFactory.cpp:17:0:
/home/pi/Desktop/alexa-avs-sample-app/samples/wakeWordAgent/src/KittAiSnowboyWakeWordEngine.h:18:28: fatal error: snowboy-detect.h: No such file or directory
 #include "snowboy-detect.h"
                            ^
compilation terminated.
CMakeFiles/wakeWordAgent.dir/build.make:110: recipe for target 'CMakeFiles/wakeWordAgent.dir/WakeWordEngineFactory.cpp.o' failed
make[2]: *** [CMakeFiles/wakeWordAgent.dir/WakeWordEngineFactory.cpp.o] Error 1
CMakeFiles/Makefile2:67: recipe for target 'CMakeFiles/wakeWordAgent.dir/all' failed
make[1]: *** [CMakeFiles/wakeWordAgent.dir/all] Error 2
Makefile:83: recipe for target 'all' failed
make: *** [all] Error 2

**Comment by bogdancraciun** [comment]
Ok, so I did a fresh install of the latest Raspbian image (on my RPi 3) + `sudo apt-get update` + `sudo apt-fet upgrade` (this install wiringPi) + run the `automated_installer.sh` again.
I get the following errors:
1. java client install error
`chmod: changing permissions of ‘/home/pi/Desktop/alexa-avs-sample-app/samples/javaclient/install-java8.sh’: Operation not permitted`

2. **wake word** detectors errors:
========== Getting the code for Kitt-Ai ===========
bash: cd: /home/pi/Desktop/alexa-avs-sample-app/samples/wakeWordAgent/kitt_ai: No such file or directory
fatal: could not create work tree dir 'snowboy'.: Permission denied
========== Getting the code for Sensory ===========
bash: cd: /home/pi/Desktop/alexa-avs-sample-app/samples/wakeWordAgent/sensory: No such file or directory
fatal: could not create work tree dir 'alexa-rpi'.: Permission denied

3. javaclient and companionService conf.json's and pom.xml errors
========== Configuring Java Client ==========
rm: remove write-protected regular file ‘/home/pi/Desktop/alexa-avs-sample-app/samples/javaclient/config.json’? y
rm: cannot remove ‘/home/pi/Desktop/alexa-avs-sample-app/samples/javaclient/config.json’: Permission denied
bash: /home/pi/Desktop/alexa-avs-sample-app/samples/javaclient/config.json: Permission denied

The installation guide should also mention:
- automated_script.sh needs to be run after login as root / SUDO
- otherwise, when updating the config.json for the javaclient, the user will be prompted to enter the productID, which has to be the same as the one declared on his amazon developer account

**Comment by abudobby** [comment]
@bogdancraciun How did u fix those errors above? I am stuck at those steps.

**Comment by bogdancraciun** [comment]
I haven't managed to solved the issue and (unfortunately) abandoned the project, because I didn't get help in this forum, nor could I found it elsewhere. I would suggest that you do a fresh reinstall of Raspbian and restart the installing process. Maybe you are lucky

**Comment by bogdancraciun** [comment]
I have created a custom Alexa skill on a Raspberry Pi and used an Amazon Echo dot for triggering the skill. The bad side of this approach is that I am unable to set a custom wake word with Echo dot, only Alexa, Computer, etc.
