### ISSUE TITLE
How to install java and set path in raspberry pi

### ISSUE THREAD

**Issue by RP2110** [alexa/alexa-avs-sample-app#581]

**Comment by scotthea-amazon** [comment]
Hello RP2110,
Java should already be installed in Raspbian Jessie.

**Comment by elstryan** [comment]
The automated install script all goes in a performs an installation. 

You can see this line: https://github.com/alexa/alexa-avs-sample-app/blob/master/automated_install.sh#L434 

Closing the issue for now since this doesn't look like a bug - but rather a question. Please feel free to re-open if you need anything.
