### ISSUE TITLE
Alexa "what's this" not working for my app

### ISSUE THREAD

**Issue by mph070770** [alexa/alexa-avs-sample-app#652]
Can anyone advise on how you inform Alexa that music is playing on a device? I'm using the mac alexa-avs-sample-app and when the radio is playing I can ask alexa "what's this" and she replies "it's radio xxxx". On my app she replies "no music is playing"

On my iOS app, I'm sending "playbackStarted" messages when the stream starts playing, and sync messages including the audioplayer status (with valid offsetinmilliseconds values) whenever I pause the audio etc. I get response codes of 204 for those, which suggests they are accepted by Alexa.

On the Amazon Alexa app, it shows that audio is playing and using the transport controls in the app I can start and stop my stream. Why does Alexa think nothing is playing?

Thanks

**Comment by jordan-heier** [comment]
Hi @mph070770 ,

Have you fully implemented support for all of the events in the [AudioPlayer Interface](https://developer.amazon.com/public/solutions/alexa/alexa-voice-service/reference/audioplayer)? If so could you please provide us with some request IDs so we can look more into the cause of the issue?

**Comment by mph070770** [comment]
Hi @jordan-heier, thanks for helping. I believe I have the audio interface implemented correctly. For example, sending playbacknearlyfinished correctly fetches the next track in a playlist. When you say a requestID do you mean a messageID?

**Comment by jordan-heier** [comment]
Hi @mph070770 ,

Request IDs come down in a response header called "x-amzn-requestid". In the Java sample app you can see these by going to the "alexa-avs-sample-app/samples/javaclient/logs" directory and looking through application.log.

**Comment by mph070770** [comment]
Hi @jordan-heier. Ok, understood. I think I'll have to expose the printing of those responses in my code. Can I just check - is it any response with a responseID that allows you to trace a session as most of my audioplayer responses return with a code 204 i.e. no response body? I'll also try and drill down in the java example to see if I can work out what I'm doing wrong. Thanks.

**Comment by mph070770** [comment]
Hi @jordan-heier, a responseID for a case where I tuned to BBC Radio 2 and then asked "what's this" is:

0ad848fffe5db783-000076f0-000575d3-4cec39592f528475-8764a842-13

Thanks

**Comment by mph070770** [comment]
Hi @jordan-heier, sorry to push you for comment but could you please check my responseID and see if you can determine why it's not working for me? Thank you in advance!

**Comment by keleric** [comment]
@mph070770 Sorry for the delayed response. I've looked into your request id. One thing that I noticed was that in your recognize request, you sent the following context for AudioPlayer:
`{
    "header" : {
      "namespace" : "AudioPlayer",
      "name" : "PlaybackState"
    },
    "payload" : {
      "token" : "",
      "offsetInMilliseconds" : 0,
      "playerActivity" : "FINISHED"
    }
  }`

I'm assuming that this recognize was "what's playing", though I can't be sure, since for privacy reasons that information is scrubbed from our logs. However, assuming that that's the case, I can say that the reason Alexa doesn't think anything is playing was because the token field was blank. Alexa uses the AudioPlayer context that you provide in the recognize request to determine what was playing. It's important to note that the Context objects that you send are a snapshot of what was happening on the device *just before* you send the recognize request. So, if you interrupt music to ask Alexa something, the PlaybackState should have the following payload:

`{
"token": "<currently playing token that was sent as part of the play payload>",
"offsetInMilliseconds": <how far into the song you are>,
"playerActivity": "PLAYING"
}`

Did that answer your question?

**Comment by mph070770** [comment]
Hi @jordan-heier... it was that easy! Thanks for your great support, that's all working now. I had incorrectly assumed that the sync states informed Alexa what was playing. I hadn't noticed that the recognize request also needed the player state. Thanks again.
