### ISSUE TITLE
I have made it work Alexa

### ISSUE THREAD

**Issue by psycomatis** [alexa/alexa-avs-sample-app#654]
I have made it work fine Alexa but i have to use 3 terminal one by one. Is there a way i can make it on boot startup ? im new in this trying to learn :D. do i need to make a script python? or something else

**Comment by jordan-heier** [comment]
Hi @psycomatis ,

This is not something we currently support, however it may be possible to set this up. One issue is that one of the Windows that opens is running the companionService and a user may need to sign in. While it is not totally related you may want to take a look at making the Raspberry Pi headless by [Setting up SSH & VNC](https://github.com/alexa/alexa-avs-sample-app/wiki/Setup-SSH-&-VNC). Good luck and let us know if you are able to get the app startup on boot working.

**Comment by sindhura94** [comment]
Yes! This is an issue. Everytime we intend to use Alexa, do we have to connect alexa to screen and run all the three terminals? Or is there any solution for this?

**Comment by DavidM42** [comment]
my best solution to this is RDP at this moment.
You just have to unintall the RPis installed vnc driver because of complications and install xrdp and now you can use a (pretty low performance laggy but sufficient) Remotedesktopconnection from your PC

**Comment by keleric** [comment]
If you're interested in this feature, you should create a request for it in our Feature Request space within the forums: https://forums.developer.amazon.com/spaces/185/index.html. Thanks! I'm closing this issue since we don't want to track feature requests through Github.

On another note, to make this easier, you can try switching from companion service to companion app authentication! Once you authenticate with the companion app, you don't need to start it ever again. That should bring your three terminal windows down to two, which is progress.
