### ISSUE TITLE
little-endian not supported

### ISSUE THREAD

**Issue by SasankYadati** [alexa/alexa-avs-sample-app#689]
I am using raspberry pi. After I run `mvn exec:exec` , I receive the device tokens ready message and when I click on listen, I get the following error dialog.

> line with format PCM_SIGNED 16000.0 Hz, 16 bit, mono, 2bytes/frame, little-endian not supported.

Thank you.

**Comment by 123anvar** [comment]
disable the default audio device by commenting out
#dtparam=audio=on
in /boot/config.txt

Take back up of following files if they exists or Create new if doesn't exists
/home/pi/.asoundrc and /etc/asound.conf 
with below content for using the **USB sound card for both speaker and mic**.

pcm.!default { type asym playback.pcm { type plug slave.pcm "plughw:1,0" format S16_LE } capture.pcm { type plug slave.pcm "plughw:1,0" }}

Reboot and check /home/pi/.asoundrc for only the above lines , if anything other is there remove and save the file then :
sudo /etc/init.d/alsa-utils restart

Try out and comment !!

**Comment by keleric** [comment]
We're closing this Issue since the original poster (or another commenter) hasn't yet responded to the question or request made to them 18 days ago. We therefore assume that the user has lost interest or resolved the problem on their own.
Don't worry though; if this is an error, let us know with a comment and we'll be happy to reopen the Issue.
Thanks!
