### ISSUE TITLE
Connecting to AVS with Node.js

### ISSUE THREAD

**Issue by Vikaton** [alexa/alexa-avs-sample-app#718]
I am trying to connect to the AVS API with Node.js as the client, but I keep getting a strange error while trying to read from amazon's response:

Error:
 ```
{ Error: Parse Error
 
    at TLSSocket.socketOnData (_http_client.js:411:20)
 
    at emitOne (events.js:96:13)
 
    at TLSSocket.emit (events.js:191:7)
 
    at readableAddChunk (_stream_readable.js:178:18)
 
    at TLSSocket.Readable.push (_stream_readable.js:136:10)
 
    at TLSWrap.onread (net.js:559:20) bytesParsed: 0, code: 'HPE_INVALID_CONSTANT' }
```

and here is my code:

```js
 var options = {
    url: 'https://avs-alexa-na.amazon.com/v20160207/directives',
    headers: {
      'Authorization': 'Bearer ' + JSON.parse(localStorage.getItem('CREDS')).access_token
    }
  };

  request.get(options).then((result) => {
    console.log(result)
      // localStorage.setItem('CREDS', result);
    res.send("Authenticated")
  })
```

I did some research and it said this would be an issue on Amazon's side, any workaround or fixes in the near future?

**Comment by yugoren** [comment]
Hi @Vikaton,

As far as I understand, this question is not related to the Java sample app we provide in this library. Are you trying to write your own AVS client using Node.js? If so, it is better to ask a question in the [AVS forum space](https://forums.developer.amazon.com/spaces/38/Alexa+Voice+Service.html) since this repository is for Java sample app only.

Here are some initial thoughts: If you haven't done already, you can check [this function](https://github.com/alexa/alexa-avs-sample-app/blob/master/samples/companionService/authentication.js#L165) in [our companion service](https://github.com/alexa/alexa-avs-sample-app/tree/master/samples/companionService) against how you set your `CREDS` parameter in your session. Also, your directive, even though it seems to have a well constructed header, does not have a content; you can check the examples [here](https://developer.amazon.com/public/solutions/alexa/alexa-voice-service/docs/avs-http2-requests) for a better understanding for how to construct a HTTP2 request.

**Comment by Vikaton** [comment]
I have authentication down with no problem, and Im sorry as that commented out line of code may be misleading, but let's assume I have a correct token.

so I figured that its because I am not using an http/2 client with my node code, so I used one and I got this error after a complete (?) request. I'm not trying to authenticate with the API right now, I'm just trying to connect with no errors (besides of course ones given form amazon's API):

```
   options: 
      { plain: false,
        href: 'https://avs-alexa-na.amazon.com/v1/directives',
        path: '/v1/directives',
        pathname: '/v1/directives',
        query: null,
        search: null,
        hash: null,
        hostname: 'avs-alexa-na.amazon.com',
        port: 443,
        host: 'avs-alexa-na.amazon.com',
        auth: null,
        slashes: true,
        protocol: 'https:',
        method: 'GET',
        ALPNProtocols: [Object],
        NPNProtocols: [Object],
        servername: 'avs-alexa-na.amazon.com',
        ciphers: 'ECDHE-RSA-AES128-GCM-SHA256:ECDHE-ECDSA-AES128-GCM-SHA256:ECDHE-RSA-AES256-GCM-SHA384:ECDHE-ECDSA-AES256-GCM-SHA384:DHE-RSA-AES128-GCM-SHA256:DHE-DSS-AES128-GCM-SHA256:ECDHE-RSA-AES128-SHA256:ECDHE-ECDSA-AES128-SHA256:ECDHE-RSA-AES128-SHA:ECDHE-ECDSA-AES128-SHA:ECDHE-RSA-AES256-SHA384:ECDHE-ECDSA-AES256-SHA384:ECDHE-RSA-AES256-SHA:ECDHE-ECDSA-AES256-SHA:DHE-RSA-AES128-SHA256:DHE-RSA-AES128-SHA:DHE-DSS-AES128-SHA256:DHE-RSA-AES256-SHA256:DHE-DSS-AES256-SHA:DHE-RSA-AES256-SHA:kEDH+AESGCM:AES128-GCM-SHA256:AES256-GCM-SHA384:ECDHE-RSA-RC4-SHA:ECDHE-ECDSA-RC4-SHA:AES128:AES256:RC4-SHA:HIGH:!aNULL:!eNULL:!EXPORT:!DES:!3DES:!MD5:!PSK',
        agent: [Object] } },
  statusCode: 403 }
events.js:163
      throw er; // Unhandled 'error' event
      ^

Error: stream.push() after EOF
    at readableAddChunk (_stream_readable.js:158:17)
    at Connection.Readable.push (_stream_readable.js:136:10)
    at Connection._parentPush (/home/vikaton/frans/node_modules/http2/lib/protocol/flow.js:243:32)
    at Connection._push (/home/vikaton/frans/node_modules/http2/lib/protocol/flow.js:255:17)
    at Connection.push (/home/vikaton/frans/node_modules/http2/lib/protocol/flow.js:286:23)
    at Connection._restoreWindow (/home/vikaton/frans/node_modules/http2/lib/protocol/flow.js:115:10)
    at runCallback (timers.js:672:20)
    at tryOnImmediate (timers.js:645:5)
    at processImmediate [as _immediateCallback] (timers.js:617:5)
```
