### ISSUE TITLE
Getting all sounds to a bluetooth speaker

### ISSUE THREAD

**Issue by D3rpi** [alexa/alexa-avs-sample-app#730]
Hello,
It's not really an issue but more of an improvement/question. How do I redirect the sound from the java app to a bluetooth speaker. I currently have a bluetooth speaker in my set up, which is my primary audio sink in pulseaudio. Alexa plays some audio over bluetooth and some through the 3.5mm jack. For example music and flash briefings play over bluetooth but all the the audio prompts from the java app or alexa herself go through the audio jack.The audio cues, alarm sounds and alexa responses get played through the 3.5mm jack. Is it possible to route all the audio to the bluetooth speaker?
Thanks for reading.

**Comment by JSONMartin** [comment]
👍  Having the same issue here. Would really appreciate a patch for this!

**Comment by keleric** [comment]
Unfortunately, this isn't an easy fix. The root cause is likely that the media player used for Alexa speech is javazoom jlayer. This media player uses the Java sound api, which I believe uses the ALSA sound layer directly. VLC (the primary media player in the sample app) is nicer and allows you to specify where to direct the sound. I believe the proper fix is refactoring the audio class in its entirety. However, this is a rather significant undertaking. It is on our backlog, though!

**Comment by keleric** [comment]
Optionally, you can put all output through the 3.5mm jack, and attach a bluetooth transmitter to that! Something like this should get all the audio: https://www.amazon.com/Wireless-Bluetooth-Stereo-Adapter-Transmitter/dp/B00RHKYX7W

**Comment by D3rpi** [comment]
Thanks for the info.
