### ISSUE TITLE
Amazon Music is not working anymore

### ISSUE THREAD

**Issue by LuBlaBo** [alexa/alexa-avs-sample-app#735]
Hey there,

at first I have to say that my English is not the best... ;)
My question is about the Amazon Music Support for the Raspberry Pi.
Is there a possibility to make it run on it? Because i have imported two Songs up in the cloud and while the Service is running i was able to listen it. But after a restart over night this feature is also not longer avaiable.
Make that any sense? 
Can i register my device or is there nothing what i can do?

Thank you for any kind of help ;)

[Voice-Service Germany, Alexa on Pi3B]

~LuBlaBo

**Comment by elstryan** [comment]
Hi, 
Amazon Music is currently limited to Alexa-enabled devices that are approved for commercial distribution and use. As a result I would expect the behavior that you are seeing after a reset. It's odd that it worked for a short period - I've tried this on some test devices myself and I never get Amazon music on non commercial device. I'll keep an eye out in case we can reproduce this.

If you are developing a commercial device, please let us know.  We’d love to help.  

Otherwise you can play music through some of our other providers such as TuneIn or iHeart. 

I'll close this issue for now. Please re-open if there is anything else we can help with.
