### ISSUE TITLE
Can't play Amazon music on this device? Raspberry Pi3

### ISSUE THREAD

**Issue by Colin1964** [alexa/alexa-avs-sample-app#740]
Have managed to get Alexa-AVS-Sample-App working fine on my RPI3. Just can't seem to get Amazon music working. My Prime and Music subscription shows up in the PC based config utility of the app and if I click on an album or track in PC app the output is loud and clear from the Pi. When I try "Alexa, play some music from prime music" I get the response "This is not possible on this device"

**Comment by elstryan** [comment]
Hi, 
At this time Amazon Music is only supported for commercially approved AVS devices. If you're working on a product for commercialization we have an page where you can share info about your product. Otherwise, if this is a device for a personal project you can still use other audio providers such as iHeart radio or TuneIn. I'll resolve this issue for now. Feel free to re-open in case you need anything else from us.

**Comment by JakeStarGames** [comment]
I wish stuff like spotify would still work

**Comment by eagleoneonline** [comment]
Any insight on getting iHeart Radio working on the Alexa Pi emulator?

**Comment by jmhoraze** [comment]
during the ESC in San Jose I attended an Amazon workshop and the tutuorial specifically provided examples to play music and Tunein;
unfortunately, the folks there didn't get that working on my dev.kit ;-()
