### ISSUE TITLE
How can I setup AVS to listen constantly? (ie: I don't want to click on "Listen" every time)

### ISSUE THREAD

**Issue by benlec** [alexa/alexa-avs-sample-app#759]
Sorry this has been already asked. I never found a proper answer to this.
Basically i don't want to click there everytime i speak to AVS just like a regular Echo device does

Photo of the Button here
https://smartmirrorprojectblog.files.wordpress.com/2017/01/schermafbeelding-2017-01-13-om-20-04-09.png?w=840

NB: Listen button is now a mic.

Possible?
Thanks a lot!
-Benjamin

**Comment by max-erler** [comment]
Hey Benjamin,

Yes, this is possible! You can use the wake word agent included in this project. Instructions on how to set it up can be found in the Raspberry Pi setup instructions: https://github.com/alexa/alexa-avs-sample-app/wiki/Raspberry-Pi

**Comment by benlec** [comment]
Well there is something I don't understand here. I followed all the tutorial until the end, activate the sensory wake word successfully, but EACH time i need to speak to Alexa invoking with Alexa word of course i need to client on the button "Tap to Speak" so it's not Hands free because once i've finished speaking to Alexa successfully, i need again to click on this button to speak again. Please see attached
![tap_to_speak](https://cloud.githubusercontent.com/assets/4939587/26147623/674d5768-3af4-11e7-87e9-07d9b191b8d8.PNG)

**Comment by yjyyjy777** [comment]
hi,benjemin 
I think you must using the latest version and open a new terminal windows to run:
cd ~/Desktop/alexa-avs-sample-app/samples
cd wakeWordAgent/src && ./wakeWordAgent -e sensory

**Comment by benlec** [comment]
Hi and thanks for your reply. Unfortunately the answer is incorrect.
1°) I have the latest version (see the Microphone icon which was introduced in latest release)
2°) See the Sensory enablement on the windows in the background on my screenshot

Do YOU have the same behavior as me or am I the only one? Is this expected behavior?

**Comment by benlec** [comment]
No one as no clue on this one? Thanks in advance

**Comment by smand90** [comment]
I am struck with same thing , can someone please reply with steps to follow

**Comment by jordanwalsh23** [comment]
Why aren't you using the wakeWordAgent? That way you can just state the
wake word e.g. 'Alexa' and the system will start listening.

**Comment by benlec** [comment]
@jordanwalsh23 I am using the Alexa wake word. But please re-read my description. the AVS works only when you click on the Microphone icon, then if you say ALEXA then it starts listening

**Comment by jordanwalsh23** [comment]
What I think is a bit odd is that the window that you are looking at with the microphone is run by executing `mvn exec:exec` from the javaClient.  The wakeWordAgent runs along side this to essentially click that button for you.

With the wakeWordAgent running you should simply be able to say the word 'Alexa' to your microphone and it should automatically start listening.  With the tools provided there is no need to ever actually click the button.

If you don't see any output content in the wakeWordAgent tab, then I'd suggest there's an issue with your microphone configuration.

**Comment by yugoren** [comment]
Hi @benlec,

Following up on the last answer by @jordanwalsh23, I suspect that the wake word is not working properly in your setup and activating voice capture automatically. Could you try saying "Alexa, tell me a joke" to your setup while paying attention to the terminal that has the wake word running? If everything goes properly, you should see some recognition event there. If nothing of that sort appears, it is most likely Sensory is not picking up the wake word. This might be due to a hardware issue with your microphone or software issue with its capture. For the hardware side, you said that you were able to get a response if you click the button, am I correct? In that case, you can try building/running the wake word agent with Kitt.Ai's wake word model and see if it works, because most likely, it's a software issue due to the wake word recognizer.

Coming back to the button: The reason that it's there even if the wake word agent is running is to make sure that the user has both options (think about Echo, having both the built-in wake word and button to start the interaction). Hence the button being on the sample app doesn't mean that the wake word is nonoperational.

**Comment by benlec** [comment]
>  you were able to get a response if you click the button, am I correct?
Yes!

OK I understand the use of the button then. So this app is really supposed to work even if you do not click on the MIC icon.

I guess there is a software issue. I will have a look at the other engine (Kitt.AI) but if i remember right I first tried using this and received an error, that's why i finally tried Sensory and it worked.

Anyway, I'll try Kitt.AI and let you know.

Thanks a lot for clear explanations :-) Finally! 👍

**Comment by yugoren** [comment]
@benlec: Sounds great! I'll close the issue for the moment, but feel free to re-open it if the problem persists.
