### ISSUE TITLE
How should DSN fill it out?

### ISSUE THREAD

**Issue by jacky-ge** [alexa/alexa-avs-sample-app#774]
I find the following instructions on DSN:
1、When prompted for a serial number, enter your product's serial number. For prototyping purposes we recommend using: 123456.

2、productId: Enter my_device as a string. dsn: Enter the same alphanumeric string that you entered for the unique product identifier in the products object in the server's config.js as a string. For example, use 123456. provisioningMethod: If you want to use either the Android or iOS sample app, enter companionApp. Otherwise, enter companionService.

If the DSN means device serial number, each device is not the same, even though productID is the same.  Does that mean the config.json for each device is different?

**Comment by dhpp** [comment]
Hi Jacky-ge - thanks for your question.  The DSN is important because it's used by AVS to maintain and know about a particular device's state.  For example, this is how AVS will know which alerts have been set on a particular device.

So, yes, each device should communicate with AVS using a unique SN.  The config.json approach is an example that our Java Sample App provides, so following that model, yes each device using the same product id would have a different SN in that config.
