### ISSUE TITLE
No token after login in Amazon (mvn exec:exec)

### ISSUE THREAD

**Issue by EgoLeX** [alexa/alexa-avs-sample-app#829]
Hello together,

im installing the Alexa Voice Service on Raspberry Pi with the Amazon Github manual but i had an problem.
I dont get the following Page:
https://raw.githubusercontent.com/wiki/alexa/alexa-avs-sample-app/assets/avs-device-tokens-ready.png
And i doesnt get any token in the PopUp Window. The following Error appears after connecting with the Amazon Login Page in the First Terminal (Terminal where NPM START were excecuted)

Failed to post request: connect ETIMEDOUT

Any Ideas?

**Comment by lijessi** [comment]
Could you paste the whole error log here? Are you trying to connect to AVS outside of the United States? Thanks.

**Comment by viagrawal** [comment]
I'm running into the same error.  Here's the error message I'm getting.  

pi@raspberrypi:~/Desktop/alexa-avs-sample-app/samples/companionService
$ cd /home/pi/Desktop/alexa-avs-sample-app/samples/companionService &&
npm start

> alexa-voice-service-sample-companion-service@1.0.0 start /home/pi/Desktop/alexa-avs-sample-app/samples/companionService
> node ./bin/www

This node service needs to be running to store token information
memory and vend them for the AVS app.

Listening on port 3000
Successfully retrieved registration code for
amzn1.application.0340663466d846b4b8d67cea55f82976 / 123456789
Error retrieving access token: TokenRetrievalFailure, Unexpected
failure while retrieving tokens.
Error retrieving access token: TokenRetrievalFailure, Unexpected
failure while retrieving tokens.

http.js:689
    throw new Error('Can\'t set headers after they are sent.');
          ^
Error: Can't set headers after they are sent.
    at ServerResponse.OutgoingMessage.setHeader (http.js:689:11)
    at ServerResponse.header
(/home/pi/Desktop/alexa-avs-sample-app/samples/companionService/node_modules/express/lib/response.js:700:10)
    at ServerResponse.send
(/home/pi/Desktop/alexa-avs-sample-app/samples/companionService/node_modules/express/lib/response.js:154:12)
    at ServerResponse.json
(/home/pi/Desktop/alexa-avs-sample-app/samples/companionService/node_modules/express/lib/response.js:240:15)
    at ServerResponse.send
(/home/pi/Desktop/alexa-avs-sample-app/samples/companionService/node_modules/express/lib/response.js:142:21)
    at /home/pi/Desktop/alexa-avs-sample-app/samples/companionService/app.js:47:17
    at IncomingMessage.<anonymous>
(/home/pi/Desktop/alexa-avs-sample-app/samples/companionService/authentication.js:208:17)
    at IncomingMessage.emit (events.js:117:20)
    at _stream_readable.js:929:16
    at process._tickCallback (node.js:419:13)

npm ERR! alexa-voice-service-sample-companion-service@1.0.0 start:
`node ./bin/www`
npm ERR! Exit status 8
npm ERR!
npm ERR! Failed at the
alexa-voice-service-sample-companion-service@1.0.0 start script.
npm ERR! This is most likely a problem with the
alexa-voice-service-sample-companion-service package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node ./bin/www
npm ERR! You can get their info via:
npm ERR!     npm owner ls alexa-voice-service-sample-companion-service
npm ERR! There is likely additional logging output above.
npm ERR! System Linux 4.9.28+
npm ERR! command "/usr/bin/nodejs" "/usr/bin/npm" "start"
npm ERR! cwd /home/pi/Desktop/alexa-avs-sample-app/samples/companionService
npm ERR! node -v v0.10.29
npm ERR! npm -v 1.4.21
npm ERR! code ELIFECYCLE
npm WARN This failure might be due to the use of legacy binary "node"
npm WARN For further explanations, please read
/usr/share/doc/nodejs/README.Debian

npm ERR!
npm ERR! Additional logging details can be found in:
npm ERR!     /home/pi/Desktop/alexa-avs-sample-app/samples/companionService/npm-debug.log
npm ERR! not ok code 0

**Comment by lijessi** [comment]
Hi, could you please try 'sudo apt-get install npm' and then reran the Alexa install? Thanks.

**Comment by viagrawal** [comment]
hi @lijessi - i'm on the latest version of npm and it still hit that error.  in the javascript client there was also an error on the nacl_fork_delegate that said there was a Bad NaCLhelper and that it wasn't able to open the ELF file.

**Comment by lijessi** [comment]
Are you having the same problem with https://github.com/alexa/alexa-avs-sample-app/issues/321 ? Could you please try the solution there?

**Comment by viagrawal** [comment]
no, there was an unexpected failure in trying to retrieve the tokens sadly.

when i looked at the output from the javaclient after running mvn:exec:exec, here's what I received.

[INFO] Scanning for projects...
[INFO]
[INFO] -----
[INFO] Building Alexa Voice Service Sample Java Client 20160207.4
[INFO] -----
[INFO]
[INFO] --- exec-maven-plugin:1.2.1:exec (default-cli) @ sample-java-client --- bootstrap_helper: /usr/lib/chromium-browser/nacl_helper: Cannot open ELF file! errno=2
[1:1:0630/182846.926619:ERROR:nacl_fork_delegate_linux.cc(315)] Bad NaCl helper startup ack (0 byters)
[1364:1398:0630/192803.935153:ERROR:cert_verify_proc_nss.cc(942)] CERT_PKIXVerifyCert for localhost failed err=-8179


And from the Amazon website, after giving permissions to Alexa with my app, I see an unexpected error.

**Comment by ANANDSKRISHNAN** [comment]
There was a problem connecting to the Companion Service. Trying again in 2 seconds. Please make sure it is up and running.
There was a problem connecting to the Companion Service. Trying again in 2 seconds. Please make sure it is up and running.
There was a problem connecting to the Companion Service. Trying again in 2 seconds. Please make sure it is up and running.
There was a problem connecting to the Companion Service. Trying again in 2 seconds. Please make sure it is up and running.
There was a problem connecting to the Companion Service. Trying again in 2 seconds. Please make sure it is up and running.
There was a problem connecting to the Companion Service. Trying again in 2 seconds. Please make sure it is up and running.
There was a problem connecting to the Companion Service. Trying again in 2 seconds. Please make sure it is up and running.
There was a problem connecting to the Companion Service. Trying again in 2 seconds. Please make sure it is up and running.
There was a problem connecting to the Companion Service. Trying again in 2 seconds. Please make sure it is up and running.
There was a problem connecting to the Companion Service. Trying again in 2 seconds. Please make sure it is up and running.
There was a problem connecting to the Companion Service. Trying again in 2 seconds. Please make sure it is up and running.
There was a problem connecting to the Companion Service. Trying again in 2 seconds. Please make sure it is up and running.
There was a problem connecting to the Companion Service. Trying again in 2 seconds. Please make sure it is up and running.
There was a problem connecting to the Companion Service. Trying again in 2 seconds. Please make sure it is up and running.
There was a problem connecting to the Companion Service. Trying again in 2 seconds. Please make sure it is up and running.
There was a problem connecting to the Companion Service. Trying again in 2 seconds. Please make sure it is up and running.

**Comment by ANANDSKRISHNAN** [comment]
can anyone find me a solution?

**Comment by EgoLeX** [comment]
I had solve my Problem. Its not an good Idea to run the Alexa Voice Service behind a ProxyServer.
All works fine now. I have aswell written an small starter, which works perfectly 👍 (can aswell downloaded as repository on my profile if anyone are interested in (only simple script 😄 ))
