### ISSUE TITLE
3.5 mm jack Option Through Soundcard

### ISSUE THREAD

**Issue by flash76** [alexa/alexa-avs-sample-app#853]
Hi. I just got this new Bose Color SoundLink speaker and I want to know if audio can go through it...
I am using a Raspberry Pi Zero W with a Sabrent USB Soundcard. Before I have done this using HDMI audio out. But can I use the 3.5 mm audio jack/AUX port on the soundcard by selecting the 3.5 mm option in the installer for the speaker?

**Comment by namanmittal-namanm** [comment]
Hi @flash76 You can try using 3.5mm jack and if you dont get sound output or any error please feel free to ask again.

**Comment by laojiang1614** [comment]
@namanmittal-namanm if 3.5mm has the audio,but when it is sent to the CX20921,there are no audio  out.DO you know why?

**Comment by dhpp** [comment]
Hi, I can also confirm that our experience developing for the pi that it's more work to get audio input and output via USB.  Generally, you will need to look into updating the ALSA configuration on the device to use the specific USB devices.  If you can use the 3.5mm jack, our advice would be to go with that.  Otherwise, this is a pi / ALSA question.

**Comment by celinval** [comment]
Closing this issue since there hasn't been any activity for a while. Please feel free to re-open the issue if the problem persists.
